akka/akka.io

community/index.md

update project and Akka versions to latest release

Update version of community library flow

---

.gitignore
community/index.md

* see https://github.com/akka/akka/issues/16619

+ akka-persistence-chronicle: new plugin contribution

---

_includes/download.html

Will there be a confusion about java 7 and java 8 being supported?

Clarify that the dist downloads are for java also

---

community/index.md

yet another minor version update

Community projects: update version of project 'flow'

---

_includes/download.html

fix release date of akka 2.3.11

---

community/index.md

- akka-persistence-kafka 0.4
- akka-analytics 0.3
- streamz 0.3
- eventuate 0.2

New releases

---

team/index.md

add Martynas to team

---

community/index.md

I've added my akka-http lib to community libs

added akka-http-extensions

---

community/index.md

As requested in https://groups.google.com/forum/#!topic/akka-user/fE6dn5dSKM4
Thanks a lot!

Added CurioDB to 'Projects Using Akka'

---

community/index.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/akka/akka.github.com/231)

please add gearpump to Akka community projects

---

community/index.md

akka-log4j 0.3.2 for Akka 2.4-M3

Upgrade version of akka-log4j on community page

---

community/index.md

As 1.0 stable is out,I also updated my akka-http-extensions lib

updated version of akka-http-extensions

---

news/_posts/2015-08-14-akka-2.4-M3-released.md

14th was the date the announcement was written, so next week means the 21st

Fixed typo in planned RC1 date

---

community/index.md

Update for plugin release 1.0.0

---

community/index.md

It's been a while, thought with the release of Akka 2.4.0 coming, I updated the version information..

Updated to the latest version and location information for jdbc and inmemory stores

---

_includes/download.html
docs/index.md

I had forgotten to bump download links in the preview PR, bumping now.

Update download links to 2.3.14

---

_includes/download.html

Fun fact, we've been forgetting to update this size since 2.3.1 ;)

Update size of released packages

---

community/index.md

First version compiled against 2.4.0.  Congrats on the major release!
Thanks!

Update to latest version of plugin

---

community/index.md

Updated available version and added details on author

Updated Spray-Funnel description

---

docs/index.md
news/_posts/2015-12-23-akka-streams-2.0.1-released.md

Please have a look if you have a second @rkuhn .
It's not dead serious as you see, maybe that's my too long day speaking in a funny way though :wink: (last year xmas release was also semi serious :-))

2.0.1 release of streams

---

community/index.md

Updated versions and release dates for the JDBC and InMemory plugin.

Update plugins for JDBC and InMemory plugin

---

_includes/download.html
_includes/footermenu.html
_includes/headerbottom.html

Added Lightened Icon to footer. Replaced references to Typesafe, Updated URLs. Added lightened.com to GA snippet.

Lightbend Updates

---

community/index.md

Updated akka-persistence-jdbc and akka-persistence-inmemory version and latest change dates. Please merge.

Updated version numbers of plugins

---

community/index.md

Journal plugin for Couchbase added to the Journal plugins section

Add Couchbase Plugins for Akka Persistence

---

community/index.md

See https://github.com/lomigmegard/akka-http-cors for more info.

Add the akka-http-cors project to the list of Akka HTTP extensions.

---

_includes/download.html
_includes/footer.html
_layouts/docs.html
docs/index.md
news/_posts/2016-04-01-akka-2.4.3-released.md
resources/stylesheets/base.css
versions.json

Announce 2.4.3

---

team/index.md

I think the time has come ... ;)

Add me, make Patrik team lead, retire Roland

---

_includes/footer.html

Removed duplicate `akka-typed-experimental` from `akkaLatestProjects` list

Removed duplicate artifact

---

_includes/frontpage.html

update rss to new blog

---

404.html
README.md

Updated the link of the akka.io website in the README.md file

Updated Readme.md and fix the issue #328

---

community/index.md

Add reference to akka-persistence-titan plugin

Add reference to akka-persistence-titan plugin

---

community/index.md

Cover the features of the latest 0.5 release

Update description of the streamz project

---

404.html

Commit aae7debe11b1094a2054ca82df3031b75e5dcd51 removed the ending `>`
of a tag. Also remove an unnecessary `</p>`.

Fix broken markup

---

_includes/download.html
_includes/footer.html
docs/index.md
news/_posts/2016-11-18-akka-2.4.13-released.md
versions.json

DONT MERGE YET, needs an url to HTTP release first.

2.4.14 released

---

_includes/footer.html
docs/index.md
news/_posts/2016-11-22-akka-http-10.0.0-released.md

Akka HTTP 10.0.0 "X"

---

_includes/download.html
docs/index.md
versions.json

seems like we never updated this when 2.3.16 was released

update links to 2.3.16

---

_includes/footer.html

for a quick fix this should be enough, however I think it's probably a better idea to download & parse version.json.

quick fix to update the akka dependencies

---

docs/index.md

This reverts commit 51d5c7952b4555b67b9db53b3f6c96e84b71704a.
#387

Revert "Link tabs for each box (current "wget" tab)"

---

404.html

#400 some front matter was missing, also, we can use templates/includes instead of building it entirely separate.

404 page not working johanandren

---

_data/alumni_team.yml
_data/team.yml
_includes/reactiveRibbon.html
index.html
resources/stylesheets/sass/_content.scss
resources/stylesheets/sass/views/_team-page.scss
team/index.md

* Removed some stuff from landing page - .net link, reactive ribbon, JVM -> Java and Scala
* Nicer looking team page - higher res member pics, some small style fixes

misc small fixes

---

_includes/footermenu.html

Refs: #416
I know you are redesigning the website, but it annoys me to see old copyright years ;)

Update copyright year to current year

---

_config.yml
_includes/blog-navbar.html
_layouts/post.html

Release day fixes 1

---

docs/index.html

the Cluster Specification is not very interesting for most users

change cluster doc link

---

community/index.html

Fixing badges and links to the Scaladex which were no longer working due to an API change.
https://github.com/akka/akka.github.com/issues/455

Fixing badges and links to the Scaladex

---

_config.yml
blog/_posts/2017-08-31-akka-http-10.0.10-released.md

Not for merge before the release is actually propagated

Announce akka-http 10.0.10

---

blog/_posts/2017-09-28-typed-cluster.md
blog/_posts/2017-10-04-typed-cluster-tools.md

example code for this post is in https://github.com/patriknw/akka-typed-blog/pull/15

blog: Typed Cluster Tools

---

blog/_posts/2017-10-13-typed-persistence.md

fixed this in the source repo, but forgot the actual post :)

remove unecessary type annotations

---

blog/_posts/2017-10-13-typed-persistence.md

As requested and announced patriknw/akka-typed-blog#18 here the blog update to reflect the final API of akka-typed 2.5.7.

Update typed persistence blog

---

get-involved/index.md

This is the new icon provided by @rasummer 
**Before**
**After**

Update forum icon svg

---

blog/_posts/2018-05-02-alpakka-team.md

Targeted to be published on Wednesday.

Announce alpakka team

---

blog/_posts/2018-06-08-akka-http-10.1.2-released.md

https://github.com/akka/akka-http/pull/2058 to be reviewed/incorporated first

Akka 10.1.2 release notes

---

docs/index.html
try-akka/index.html

* and link to more guides from Try Akka

gRPC doc box

---

index.html

Right now it is "Akka | Akka", which is a bit sparse.

Expand the index page title

---

_config.yml
blog/_posts/2018-12-07-akka-2.5.19-released.md

Will have another scan through the issues after lunch

Akka 2.5.19

---

blog/_posts/2018-12-11-alpakka-kafa-1.0-RC1-released.md

Do not merge before the artifacts are in maven central and new docs are up
Ticket for release coordination: https://github.com/akka/alpakka-kafka/issues/677

Alpakka Kafka 1.0-RC1

---

blog/_posts/2019-02-04-programming-reactive-systems.md

* there will be 2 follow up articles and therefore I used the series format

Announce the course Programming Reactive Systems

---

_config.yml
blog/_posts/2019-02-13-akka-2.5.21-released.md

Nothing too exciting in this release

Release notes for Akka 2.5.21

---

blog/_posts/2019-02-28-alpakka-kafka-1.0-released.md

Please merge only after Alpakka Kafka 1.0 release is done and the docs have been deployed.

Alpakka Kafka 1.0

---

blog/_posts/2019-03-01-alpakka-1.0-M3-released.md

Should be merged after Alpakka release is done and docs are in place.

Do not merge yet: Alpakka 1.0-M3

---

try-akka/index.html

Add redirect from '/downloads' to '/try-akka'

---

blog/news-archive.md

Fix 404 on /releases/ URL

---

blog/_posts/2015-08-21-akka-2.4.0-RC1-released.md
blog/_posts/2015-09-04-akka-2.4.0-RC2-released.md

Fix two links in wrong format.

Fix dead 2.4.0-RC1 links

---

blog/_posts/2019-04-04-alpakka-1.0-is-here.md

The release announcement for Alpakka 1.0.0! Yeah!

Alpakka 1.0.0

---

resources/stylesheets/sass/_content.scss

Show strong content as bold #595

---

index.html

Small wording fix

---

blog/_posts/2019-04-04-alpakka-1.0-is-here.md

Point canonical URL to lightbend.com

Point canonical URL to lightbend.com

---

blog/_posts/2019-05-02-alpakka-kafka-1.0.2-released.md

Add Alpakka Kafka release announcement.

Alpakka Kafka 1.0.2

---

blog/_posts/2019-06-11-scala-2.13-landed-in-akka.md

Scala 2.13 in Akka

---

blog/_posts/2019-06-11-scala-2.13-landed-in-akka.md

Akka Persistence Cassandra is updated, as well.

Add APC* to 2.13 post

---

README.md
blog/_posts/2019-09-09-akka-family-builds.md

Akka family build blogpost

---

_data/alpakkateam.yml

Adding myself to the Alpakka team page, as requested.

Add Sean to the Alpakka team

---

docs/other-releases.md

fix wrong 2.5 link in docs archive

---

blog/_posts/2017-05-05-typed-intro.md
blog/_posts/2017-05-06-typed-coexistence.md
blog/_posts/2017-05-08-typed-mutable-vs-immutable.md
blog/_posts/2017-05-12-typed-protocols.md
blog/_posts/2017-05-16-supervision.md
blog/_posts/2017-05-19-signals.md
blog/_posts/2017-05-26-timers.md
blog/_posts/2017-09-28-typed-cluster.md
blog/_posts/2017-10-04-typed-cluster-tools.md
blog/_posts/2017-10-13-typed-persistence.md

out of date note in Typed blog posts

---

_includes/youtubePlayer.html
blog/_posts/2019-12-03-akka-typed-actor-intro-video.md
resources/stylesheets/sass/views/_blog-page.scss

and first video blog post
No idea how to make that responsive/work on small screens though.

Youtube player template and first video embed

---

blog/_posts/2019-12-11-akka-26-intro.md
blog/_posts/2019-12-12-akka-26-intro.md

Intro to 26 video

---

blog/_posts/2019-12-16-akka-cluster-sharding-intro-video.md

Intro to sharding video post.

---

blog/_posts/2020-01-22-managing-blocking-video.md

Draft because it still needs the youtube id

Add 'managing blocking' video

---

blog/_posts/2020-01-22-managing-blocking-video.md

more links, from last slide

---

_data/presentations_blogs.yml
blog/_posts/2020-01-15-alpakka-kafka-2.0-released.md

Mention new Kafka flow control improvements blog post.

Kafka flow control improvements blog post

---

.travis.yml
.travis/known_hosts
_config.yml

Build master on travis and deploy to gustav

---

blog/_posts/2020-03-18-akka-sharding-kafka-video.md

Don't merge yet, we plan to publish tomorrow.

Sharding Kafka video

---

blog/_posts/2020-04-30-alpakka-2.0.0-released.md

References https://github.com/akka/alpakka/issues/2276

Alpakka 2.0

---

blog/_posts/2020-05-04-akka-persistence-cassandra-1.0.0-released.md

Akka APC 1.0 blog post

---

blog/_posts/2020-05-04-akka-persistence-cassandra-1.0.0-released.md

Too used to Github doing it for me

Real links

---

blog/_posts/2020-04-30-alpakka-2.0.0-released.md

https://www.youtube.com/watch?v=cNCHF61F5Bg

Alpakka 2 post: add video

---

.htaccess
.travis.yml
blog/external-archive.md
blog/index.md
blog/news-archive.md
docs/index.html
try-akka/index.html

Fixes https://github.com/akka/akka.io/issues/679

Use .htaccess for redirects; update Javadoc links

---

.htaccess
versions.json

I think we should eventually generate this as part of the Akka docs instead of
as part of the akka.io site, but this is the quick fix.
Refs https://github.com/akka/akka/issues/29080

Fix version overview

---

blog/_posts/2020-06-05-external-akka-cluster-dashboard.md

I think we have already promoted this in twitter. So we have it in the archives.

Akka Cluster Quickstart Dashboard

---

blog/_posts/2020-06-09-akka-persistence-jdbc-4.0.0-released.md

Announcement for Akka Persistence JDBC 4.0
Please don't merge right away. I'm targeting the release for tomorrow, 09/07.

Akka Persistence JDBC 4.0 announcement

---

blog/_posts/2020-06-25-akka-http-10.2.0-RC1-released.md

Release Akka HTTP 10.2.0-RC1

---

_config.yml
blog/_posts/2020-07-10-akka-2.6.7-released.md

Release notes

---

_config.yml
blog/_posts/2020-08-06-akka-http-10.2.0-released.md

Only merge after release is done.

Announce Akka HTTP 10.2.0

---

blog/_posts/2020-09-01-akka-projection-1.0.0-RC3-released.md

formatting: added breakline after 'hakkers'

---

blog/_posts/2020-10-22-replicated-event-sourcing-data-modelling.md

Second replicated event sourcing video

---

docs/index.html

Add Akka Projections to the docs overview page

---

.htaccess

I just realised my earlier local changes were overwritten (ofc).

Redirects to the Akka Platform Guide on TechHub

---

blog/_posts/2021-01-21-akka-projection-1.1.0-released.md

Hold on with merge as artifacts are not yet in maven central

Akka Projections 1.1.0 release

---

blog/_posts/2021-02-08-akka-grpc-1.1.0-released.md

References https://github.com/akka/akka-grpc/issues/1129

Draft Akka gRPC 1.1.0

---

_data/team.yml
blog/_posts/2018-02-23-akka-2.5.10-released.md
blog/_posts/2020-06-09-akka-persistence-jdbc-4.0.0-released.md
team/index.md

Someone pointed out to me that we have a unpaired closing div tag (see screenshot). This PR removes it. 
I'm taking the opportunity to update my own twitter/github handle. I forgot to do it when I changed my handle.

Remove trialing div and update team handle

---

blog/_posts/2021-04-23-akka-projection-1.2.0-released.md

Akka Projections 1.2.0

---

blog/_posts/2021-05-15-alpakka-kafka-2.1.0-released.md

Alpakka Kafka 2.1.0 release announcement

---

_data/alumni_team.yml
_data/team.yml

update team page

---

_config.yml
blog/_posts/2021-06-08-akka-2.6.15-released.md
blog/_posts/2021-06-10-akka-2.6.15-released.md

Release akka 2.6.15

---

blog/_posts/2021-08-19-akka-2.6.16-released.md

add notice about deserialization warning for new RegionStopped message

---

_includes/lightbendBanner.html

@ennru This swaps out the news banner promo at the top of the page. Adding Akka Insights and removing Akka Cloud Platform.

News Banner - Added Akka Insights, removed Akka Cloud Platform

---

index.html
resources/stylesheets/sass/views/_start-page.scss

@ennru per a request, I've removed a couple of logos from the homepage. Also tweaked the language above the logos.
Could you have this reviewed and deployed. Many thanks.

remove certain logos

---

blog/_posts/2022-10-26-akka-22.10-released.md

typo EventSourcedBehavior
