community/index.md

There was a missing closing </code> tag in the Eventuate section of http://akka.io/community/ (which didn't show up as formatting problem in the preview)

Fix formatting problems

---

news/_posts/2015-11-27-akka-2.4.1-released.md

Missed out on the TransparentExponentialBackoffSupervisor in the initial announcement of 2.4.1

2.4.1 missed issue

---

get-involved/index.md

community-contrib was renamed to easy-to-contribute

fix link pointing to github issues on get involved page

---

get-involved/index.md

`easy-to-contribute` label was renamed to `community`

Fixed github label 'easy-to-contribute' renamed to 'community'

---

404.html

Couldn't figure out how (if possible) to get the jekyll placeholder to work in the 404 page so replaced with site-relative links, which worked locally with jekyll.

Fixed menu links and icons on 404 page

---

_includes/footer.html

It seems the `akka-http-teskit` should've been moved with [the rest](https://github.com/akka/akka.github.com/commit/4896ac0f82d5af5f0a87905bbc0f391b6709e919) of `akka-http` dependencies to the separate list, but wasn't.
Noticed by Gavin Baumanis (@thespidernet ?) on the akka-user mailing list.

Move akka-http-testkit to the rest of HTTP deps

---

docs/index.md

The commit that introduced the second “Scala” was more than year ago, so I'm slightly worried it's not a typo but some sort of unknown to me convention for how you write Scala version ranges in titles or something. :) I'm sorry for bothering you if it is.

Remove second 'Scala' from the title on the docs index

---

docs/index.md
resources/javascript/akka.io.js

Add wget tab with direct urls to artifacts, by popular demand - as a replacement to the distribution zip file.

Add wget tab to dependencies site

---

blog/tags.md

Not sure what JB is and how it is configured but it doesn't work automatically
for some reason.

Fix links on /blog/tags page (for subpath installations)

---

docs/index.html

Links to Akka HTTP point to a non (anymore) existing URL.

Fix Akka HTTP doc links

---

blog/_posts/2017-05-25-akka-http-10.0.7-released.md

Right now it looks a bit unstructured.

Fix headers in Akka HTTP 10.0.7 announcement

---

.gitignore
_config.yml

Bundler recommends to install stuff to the project's local directory:
bundle install --path vendor/bundle
But after that running jekyll fails, because it can not parse blog entries from the `vendor` directory. This adds ignores to the git and jekyll configs to ignore these.

Ignore bundler install output

---

blog/_posts/2017-09-28-typed-cluster.md

First blog post of three in a series about the new Typed Cluster and Persistence APIs.
Full source code of examples in https://github.com/patriknw/akka-typed-blog/pull/14

Blog post: Typed Cluster API

---

blog/_posts/2017-09-28-akka-2.5.5-released.md

Please merge https://github.com/akka/akka.github.com/pull/463 before this one, as we point to it in this news item

Release 2.5.5 with JDK9 and juc.Flow support!

---

blog/_posts/2017-12-22-akka-http-10.1.0-RC1-released.md

Only merge after the actual release.
Release stats should be updated once again with the final numbers.

Releasing Akka HTTP 10.1.0-RC1

---

blog/_posts/2017-12-22-akka-http-10.1.0-RC1-released.md

Note also that there’s also a redirect missing from /news/... -> /blog/news/...

Fix typo in Akka HTTP 10.1 RC1 post

---

index.html

The anchor doesn't exist any more after https://github.com/akka/akka/pull/23210, this seems like the best alternative. Maybe @raboof can check it.

Update link to 'Actor model'

---

docs/index.html

Fixes #489 
But it seems something is anyways wrong with the rendered Scaladocs HTML

Scala 2.12 style scaladoc links

---

docs/index.html

Reverts akka/akka.github.com#490

Revert "Scala 2.12 style scaladoc links"

---

_config.yml

Hi, 
according to [akka-http-10.1.0-released](https://akka.io/blog/news/2018/03/08/akka-http-10.1.0-released), I guess this needs to be updated, right?
I hope this changes the version on this page: https://akka.io/docs/ (see akka-http).
Matthias

update latest akka-http version

---

resources/stylesheets/sass/views/_docs.scss

this is noticeable on an iPhone 5 f.e.:
I think this fixes it, but I'm no frontend expert so please check thoroughly :)

Fix language select box breaking out of its container on small screens

---

docs/index.html

Page layout changed from having an index page per package, to having to list that index from the top-level index.html

Fix scala 2.12.7 api doc links

---

docs/index.html

Partially reverts #526 since we updated the scaladocs

Change scala api links to 2.12-scaladoc style again

---

blog/_posts/2018-10-07-akka-2.5.18-released.md

`Rename ActorContext#schedule with scheduleOnce` change has been forgotten in the release notes

Add missing change in Akka Typed API

---

_config.yml

Hi, I didn't see a CONTRIBUTING.md file.
I just noticed that the `current_akka_http_version` on https://akka.io/docs/ is 10.1.7 so I figured I'd open this quick PR to update it. I'm also going to comment on https://github.com/akka/akka-http/issues/2466 to add this to the release train checklist. Let me know if I missed something. Thanks!

Bump current_akka_http_version to 10.1.8

---

_includes/headertop.html

Canonical url is specified by adding canonical_url in the page preample

Allow for specifying a canonical url (to any page)

---

blog/_posts/2018-01-11-akka-2.5.9-released-2.4.x-end-of-life.md

* because old migration guides are removed

use 2.5 instead of current in link to migration guide

---

blog/_posts/2017-10-23-native-akka-streams-in-spring-web-and-boot-via-alpakka.md
blog/_posts/2018-05-02-alpakka-team.md
blog/_posts/2018-08-30-alpakka-towards-1.0.md
blog/_posts/2019-03-19-akka-management-1.0.0-released.md
blog/_posts/2019-04-03-akka-2.5.22-released.md
docs/index.html
index.html

Let links point directly to the new home.
https://github.com/akka/akka.github.com/issues/607
https://github.com/akka/akka.github.com/issues/568
https://github.com/akka/akka.github.com/issues/561
https://github.com/akka/akka-management/pull/553
https://github.com/akka/akka-grpc/pull/583

Change links from developer.lightbend.com to doc.akka.io

---

blog/_posts/2019-06-11-scala-2.13-landed-in-akka.md

Update the link to Akka Persistence Cassandra on the recent blog post so it points to the akka.io docs.

Link to Akka Persistence Cassandra on akka.io

---

docs/index.html

The dependency info for different build tools is nowadays well present in all Akka docs and should be dropped from the overview page
(I'm referring to this kind of box on https://akka.io/docs/)

Drop the dependency info boxes

---

_data/presentations_blogs.yml
_includes/presentations-blogs-item.html
presentations-blogs/index.md

Add a page where presentations and blogs can be referenced.
It is not referenced from any other page until we collect a useful amount of entries for it.
In Alpakka we have [Webinars, Presentations and Articles](https://doc.akka.io/docs/alpakka/current/other-docs/webinars-presentations-articles.html). It would be great if we create a central place for external resources that get collected over time.

Presentations and blogs page

---

_config.yml
docs/index.html
docs/other-releases.md

To be merged after switching the `current` symlinks

update version and docs index to Akka 2.6.0

---

_includes/headerbottom.html
_includes/youtubePlayer.html
resources/javascript/akka-io.js
resources/stylesheets/sass/modules/_oneTrust.scss

Have YouTube embedded players respect privacy policy.
The Author continues to add videos in exactly the same way as before, the code now inserts a link to the video on YouTube when the page first loads. This is the first fallback incase JavaScript doesn't load, throws errors etc. Most users should never see this.
Once the cookie compliance code loads, it swaps out the original link with an accept cookies dialogue. This dialogue also provides a link to the YouTube video for those that might not wish to accept cookies. 
Once cookies have been accepted the video loads. You only have to accept cookies once on the site, so for regular visitors they will likely just see the video. 
To test locally, you need to add `-test.js` to the end of the OneTrust JS include: …

Videos only get embedded in the blog if cookies have been approved

---

.htaccess

As it turns out `Redirect` applies to all paths starting with the given URL.
https://httpd.apache.org/docs/2.4/mod/mod_alias.html#redirect
This requires exaxct match for some redirects to apply.

require exact match for redirects

---

versions.json

I fixed some of these directly on Gustav before to bring the version warnings back.

Akka 2.6 instead of all old version, remove historic packagings

---

versions.json

The 'outdated' marking leads the warning: "This version of Akka is
outdated and not supported! Please upgrade to version 2.6.5 as soon
as possible.
That is too strong for Akka 2.5. Leaving the 'instead' so we can later
update `warnOldDocs.js` to add a milder warning pointing people to
2.6.

Don't mark Akka 2.5 'outdated'

---

_includes/youtubePlayer.html

I notices that there is no spacing between the video and the next text. This will add some spacing.

Adds a breakline after video widget

---

.htaccess

It seems remaining posts have been moved to category "article" in
50e81f67bc29cf2803b9cc57818a8b5d9d5aeb4b..
One of those posts is now under `/blog/news` (2019-02-04-programming-reactive-systems)
so for this one the redirect will be wrong.
Refs #756

fix links under the assumption that all posts have been moved to category "article"

---

_includes/disqus.html
_includes/footermenu.html
_includes/headerbottom.html
cookie/index.html
resources/javascript/akka-io.js
resources/stylesheets/sass/modules/_oneTrust.scss

@ennru @patriknw 
This updates the akka.io website to the latest cookie banner code. It uses geo-location to present Californian users with CCPA specific language in the preference center, cookie banner and footer link. The rest the world see's existing GDPR messaging. I'll be sending over a PR for the Akka Docs also.
Also the preference center and cookie banner has a new look and feel as part of this upgrade, that all visitors will now see. 
Example of the Preference center newer look:
In California, the `Cookie Settings` link in the footer is automatically replaced with a `Do Not Sell My Personal Information` per CCPA. As a result of the longer link, I needed to tweak the footer column sizes.

upgrade cookie banner and preference center for CCPA

---

.htaccess

These URL haven't been announced publicly, so we can remove them to have a place for the WIP deployment reachable.

Skip redirecting Platform Guide URLs

---

get-involved/index.md

Since Gitter is now part of Matrix, going forward Matrix is probably
more familiar to many people.

Link to Matrix as well

---

docs/index.html

The "Getting Started" section doesn't really fit when we add the cloud products.
We'll work on the "Try Akka" page to divert users depending on the way the want to hakk.﻿

Show Akka Products on /docs page
